### ISSUE TITLE
Falsche Ausgabe der Testdaten in chap_6/keras_iris_classification_with_evaluation.ipynb

### ISSUE THREAD

**Issue by eli04nzi** [deeplearning-mit-tensorflow-keras-tfjs/2020_Zweite_Auflage#3]
Hallo,

im letzten Block werden die Ergebnisse nicht richtig ausgegeben. 

Es wird
```
Iris mit den Eigenschaften [5.1 3.5 1.4 0.2] gehört zur Klasse: Iris-setosa
Iris mit den Eigenschaften [4.9 3.  1.4 0.2] gehört zur Klasse: Iris-virginica
Iris mit den Eigenschaften [5.1 3.5 1.4 0.2] gehört zur Klasse: Iris-setosa
Iris mit den Eigenschaften [5.9 3.  5.1 1.8] gehört zur Klasse: Iris-versicolor
```
ausgegeben, obwohl im Array die Reihenfolge  `[5.1,3.5,1.4,0.2], [5.9,3.,5.1,1.8], [4.9,3.,1.4,0.2], [5.8,2.7,4.1,1.]` ist. 
Dies kommt zustande, weil es nur einen Zähler gibt, der aber den Index der Prediction enthält ( deswegen taucht der 4. Teil im Array auch gar nicht in der Ausgabe, weil der Index ja nur 3 Kategorien hat). Man müsste einen zweiten Index einführen und so sieht meine Lösung dafür aus:
```
c = 0
for i in index_max_predictions:
    print(f"Iris mit den Eigenschaften {test_data[c]} gehört zur Klasse: {iris_label_array[i]}")
    c = c+1
``` 

Ich hoffe das stimmt so weit und würde mich über die Behebung des Fehlers freuen
Elias

**Comment by deeplearning-mit-tensorflow-keras-tfjs** [comment]
Hallo Elias,
vielen herzlichen Dank für den Hinweis! 
Wir haben den Code wie folgt verändert:

```
for index, e in enumerate(index_max_predictions):
    print("Iris mit den Eigenschaften {} gehört zur Klasse: {}".format(
         test_data[index],
         iris_label_array[e]))
```
Die Ergebnisse werden nun korrekt ausgegeben. 
Alles Gute zum neuen Jahr, viele Grüße und viel Spaß bei Coden 😄!

Alassane & Matthieu
