### ISSUE TITLE
Paketname wget müsste python-wget sein

### ISSUE THREAD

**Issue by andixtaf** [deeplearning-mit-tensorflow-keras-tfjs/2020_Zweite_Auflage#4]
Im Kapitel 4, numpy_examples wird gesagt man soll wget mit conda installieren. Danach konnte das File aber nicht ausgeführt werden, immer mit der Meldung dass das Paket wget nicht gefunden werden kann. In PyCharm wird zwar alles korrekt angezeigt aber bei der Ausführung kam es zu dem Fehler, sowie der Versuch das File aus dem Terminal heraus auszuführen (entsprechende env aktiviert)
Erst mit der folgenden Anweisung hat es geklappt:

`conda install -n geo conda-forge::python-wget`

 Danach konnte das File erfolgreich ausgeführt werden.

**Comment by alnd01** [comment]
Danke sehr!
