### ISSUE TITLE
Meldung aus Kapitel 6 LSTM Kursvorhersage

### ISSUE THREAD

**Issue by SusannPeterVogt** [deeplearning-mit-tensorflow-keras-tfjs/2020_Zweite_Auflage#6]
Leider funktioniert bei mit der Beispielcode im Jupiter_Notbook nicht es gibt beim LSTM folgende Meldung:

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/var/folders/fd/7jq5f1yx7tj5w54g9cqb5qbm0000gn/T/ipykernel_81585/1974042651.py in <module>
      1 # Definition des Keras Modells
      2 stock_model = Sequential()
----> 3 stock_model.add(LSTM(10,input_shape=(DAYS_BEFORE,1),return_sequences=True))
      4 stock_model.add(LSTM(5,activation="relu"))
      5 return_sequences=True

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py in add(self, layer)
    176           # and create the node connecting the current layer
    177           # to the input layer we just created.
--> 178           layer(x)
    179           set_inputs = True
    180 

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py in __call__(self, inputs, initial_state, constants, **kwargs)
    621 
    622     if initial_state is None and constants is None:
--> 623       return super(RNN, self).__call__(inputs, **kwargs)
    624 
    625     # If any of `initial_state` or `constants` are specified and are Keras

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    840                     not base_layer_utils.is_in_eager_or_tf_function()):
    841                   with auto_control_deps.AutomaticControlDependencies() as acd:
--> 842                     outputs = call_fn(cast_inputs, *args, **kwargs)
    843                     # Wrap Tensors in `outputs` in `tf.identity` to avoid
    844                     # circular dependencies.

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent_v2.py in call(self, inputs, mask, training, initial_state)
    891   def call(self, inputs, mask=None, training=None, initial_state=None):
    892     # LSTM does not support constants. Ignore it during process.
--> 893     inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
    894 
    895     if isinstance(mask, list):

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py in _process_inputs(self, inputs, initial_state, constants)
    796       initial_state = self.states
    797     else:
--> 798       initial_state = self.get_initial_state(inputs)
    799 
    800     if len(initial_state) != len(self.states):

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py in get_initial_state(self, inputs)
    604     if get_initial_state_fn:
    605       init_state = get_initial_state_fn(
--> 606           inputs=None, batch_size=batch_size, dtype=dtype)
    607     else:
    608       init_state = _generate_zero_filled_state(batch_size, self.cell.state_size,

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py in get_initial_state(self, inputs, batch_size, dtype)
   2312   def get_initial_state(self, inputs=None, batch_size=None, dtype=None):
   2313     return list(_generate_zero_filled_state_for_cell(
-> 2314         self, inputs, batch_size, dtype))
   2315 
   2316 

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py in _generate_zero_filled_state_for_cell(cell, inputs, batch_size, dtype)
   2750     batch_size = array_ops.shape(inputs)[0]
   2751     dtype = inputs.dtype
-> 2752   return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
   2753 
   2754 

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py in _generate_zero_filled_state(batch_size_tensor, state_size, dtype)
   2766 
   2767   if nest.is_sequence(state_size):
-> 2768     return nest.map_structure(create_zeros, state_size)
   2769   else:
   2770     return create_zeros(state_size)

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py in map_structure(func, *structure, **kwargs)
    533 
    534   return pack_sequence_as(
--> 535       structure[0], [func(*x) for x in entries],
    536       expand_composites=expand_composites)
    537 

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py in <listcomp>(.0)
    533 
    534   return pack_sequence_as(
--> 535       structure[0], [func(*x) for x in entries],
    536       expand_composites=expand_composites)
    537 

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/recurrent.py in create_zeros(unnested_state_size)
   2763     flat_dims = tensor_shape.as_shape(unnested_state_size).as_list()
   2764     init_state_size = [batch_size_tensor] + flat_dims
-> 2765     return array_ops.zeros(init_state_size, dtype=dtype)
   2766 
   2767   if nest.is_sequence(state_size):

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py in zeros(shape, dtype, name)
   2347         # Create a constant if it won't be very big. Otherwise create a fill op
   2348         # to prevent serialized GraphDefs from becoming too large.
-> 2349         output = _constant_if_small(zero, shape, dtype, name)
   2350         if output is not None:
   2351           return output

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py in _constant_if_small(value, shape, dtype, name)
   2304 def _constant_if_small(value, shape, dtype, name):
   2305   try:
-> 2306     if np.prod(shape) < 1000:
   2307       return constant(value, shape=shape, dtype=dtype, name=name)
   2308   except TypeError:

<__array_function__ internals> in prod(*args, **kwargs)

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/numpy/core/fromnumeric.py in prod(a, axis, dtype, out, keepdims, initial, where)
   3050     """
   3051     return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
-> 3052                           keepdims=keepdims, initial=initial, where=where)
   3053 
   3054 

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     84                 return reduction(axis=axis, out=out, **passkwargs)
     85 
---> 86     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     87 
     88 

~/opt/anaconda3/envs/Env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in __array__(self)
    734   def __array__(self):
    735     raise NotImplementedError("Cannot convert a symbolic Tensor ({}) to a numpy"
--> 736                               " array.".format(self.name))
    737 
    738   def __len__(self):

NotImplementedError: Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array.

Was mache ich falsch?

**Comment by alnd01** [comment]
### NB: Python-Installation auf M1
Sollten Sei einen M1 Prozessor einsetzen, verweisen wir für die Installtion auf folgende Seiten:<br>
https://betterdatascience.com/install-tensorflow-2-7-on-macbook-pro-m1-pro/<br>
https://www.examplefiles.net/cs/620349<br>
https://towardsdatascience.com/accelerated-tensorflow-model-training-on-intel-mac-gpus-aa6ee691f894<br>
https://naturale0.github.io/2021/01/29/setting-up-m1-mac-for-both-tensorflow-and-pytorch<br>

Im wesentlichen können Sie wie folgt vorgehen:<br>
```conda install nomkl bzw. pip install nomkl```<br>
```conda install -c apple tensorflow-deps -y```<br>
```python -m pip install tensorflow-macos```<br>
```pip install tensorflow-metal```

**Comment by alnd01** [comment]
Guten Tag,
wenn Sie folgende Fehlermeldung bekommen, dann haben Sie wahrscheinlich eine mit Ihrer Tensorflow-version nicht kompatible numpy-Version: <br>`Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported`. <br> In diesem Fall können Sie entweder auf die Numpy-version 19.1 downgraden oder auf die Tensorflow-Version upgraden (>= 2.6).<br> cf. https://github.com/tensorflow/models/issues/9706
